### PR TITLE
Deprecate [:host][/ssh_port] client host arguments

### LINKED ISSUE #68: Restraint client accepts wrong host argument
In restraint 0.1.45 the host argument was,
```
-t, --host <recipe_id>=[user@]hostname[:port][/ssh_port]
```
In 0.2.0 is,
```
-t, --host=<recipe_id>=[<user>@]<host>[:ssh_port]
```
`[<user>@]<host>[:ssh_port]` is used by the ssh client, but `<host>:ssh_port` is not valid syntax, and parsing shouldn't succeed if this format is used.

Instead of just failing with this format, we can hide these arguments, warn about deprecation just when they are used, and ignore them after parsing.
This will give user visibility about these changes and the client will still work if the old format is used.

### PR DESCRIPTION
**Pull request by danrodrig**
Deprecate the host format in 0.1.45 keeping it backwards compatible.

- Accet the `[:host][/ssh_port]` arguments in the host option warning about deprecation
- Ignore `[:host][/ssh_port]` after parsing
- Fail parsing when host argument doesn't match format

Closes #68 
Relates to #12

### CODE REVIEW

File: src/client.c [hunk 1]
```diff
@@ -1678,25 +1678,47 @@ pretty_results (gchar* run_dir)
...
-    GRegex *regex;
-    GMatchInfo *match_info;
+    GMatchInfo  *match_info;
+    GRegex      *regex;
+    gchar      **ssh_destination;
+
+    g_return_val_if_fail (connect_uri != NULL, NULL);
+
+    /* [user@]hostname[:port][/ssh_port] */
+    regex = g_regex_new ("^(([\\w\\.\\-]+)@)?([\\w\\.\\-]+)((:\\d+)?(/\\d+)?)?$", 0, 0, NULL);
```
Comment (StykMartin) [inline src/client.c:1691]: We are missing proper escape in `(/\\d+)?`
First character is not escaped

File: src/client.c [hunk 2]
```diff
@@ -1719,6 +1719,9 @@ static gboolean add_recipe_host(const gchar *value, AppData *app_data,
     recipe_data->connect_uri = connect_uri;
     recipe_data->rhost = parse_host(recipe_data->connect_uri);
 
+    if (recipe_data->rhost == NULL)
+      result = FALSE;
+
```
Comment (StykMartin) [inline src/client.c]: You are getting rid of this change in this PR.
We can drop this commit.

File: src/client.c (hunk 1 above)
Comment (danrodrig) [reply src/client.c:1691]: > First character is not escaped 

The forward slash? It doesn't need escape here.

Comment (cbouchar) [reply src/client.c:1691]: Martin:  If you look at his example, / is handling the / preceding ssh_port.

File: src/client.c [hunk 3]
```diff
@@ -1705,22 +1727,38 @@ static gboolean add_recipe_host(const gchar *value, AppData *app_data,
...
+        result = TRUE;
+    } else {
+        result = FALSE;
+    }
 
     g_free (id);
-    g_strfreev (args);
+    g_free (connect_uri);
+    g_free (args);
```
Comment (cbouchar) [inline src/client.c:1760]: According to glib doc, you should be using g_strfreev to free data allocated with g_strsplit.

File: src/client.c [hunk 4]
```diff
@@ -1705,22 +1727,38 @@ static gboolean add_recipe_host(const gchar *value, AppData *app_data,
...
+        g_free (ssh_destination);
+
+        result = TRUE;
+    } else {
+        result = FALSE;
+    }
 
     g_free (id);
-    g_strfreev (args);
+    g_free (connect_uri);
```
Comment (cbouchar) [inline src/client.c:1759]: If you are no longer doing g_strdup, do you still need to free connect_uri?

Comment (danrodrig) [reply src/client.c:1759]: We are freeing the strings in `args` here.

File: src/client.c (hunk 3 above)
Comment (danrodrig) [reply src/client.c:1760]: From `g_strsplit()`,
> Returns a newly-allocated NULL-terminated array of strings. Use g_strfreev() to free it.

There is nothing in `g_strsplit()` requiring `g_strfreev()`, it's only for convenience.

From g_strfreev(),
> Frees a NULL-terminated array of strings, as well as each string it contains.

We are using the "strings" allocated by `g_strsplit()` in `id` and `connect_uri`, and we are freeing them ourselves. We only need to free the array of strings.

File: src/client.c (hunk 4 above)
Comment (cbouchar) [reply src/client.c:1759]: I believe you missed my question.  Not sure how connect_uri variable relates to args in your response.

File: src/client.c (hunk 3 above)
Comment (cbouchar) [reply src/client.c:1760]: Since we're consecutively freeing id, connect_uri and args, why not just use g_strfreev()?

Comment (danrodrig) [reply src/client.c:1760]:
```
args = g_strsplit(value, "=", 2);
if (g_strv_length(args) != 2) {
    id = g_strdup_printf("%u", (*recipe_id)++);
    connect_uri = args[0];
```
If `args` has 1 string, `connect_uri` is `args[0]`, and we make `id` from `recpie_id`.

```
} else {
    id = args[0];
    connect_uri = args[1];
}
```
If `args` has 2 strings, `id` is `args[0]` and `connect_uri` is `args[1]`.

To use `g_strfreev()`, we'd need to make condition to check where `id` is pointing to. Or, duplicate the strings in `args` just for the sake of using `g_strfreev ()`, which is pointless.

Instead of duplicating the strings in `args`, we are using them directly in `id` and `connect_uri`, and we don't need extra conditions to free `id`, because that was handled already in the assignment.

Comment (cbouchar) [reply src/client.c:1760]: I see what the issue is.  Thank you for the explanation.

**Comment by danrodrig** [comment]
Before these changes, using `host:port` made ssh client fail,
```
$ ./src/restraint -t 796557=user@localhost:22 -j src/test-data/recipe.xml -n 
Using ./recipe.01 for job run
Connecting to host: user@localhost:22, recipe id:796557
** Message: 16:45:35.987: use_pty:FALSE ssh user@localhost:22 -- restraintd --port 0 --stdin

** Message: 16:45:35.994: ssh: Could not resolve hostname localhost:22: Name or service not known

One or more tasks failed [restraint-error-quark, 10]
```
With these changes, user is warn about deprecation and ssh client gets proper arguments,
```
$ ./src/restraint -t 796557=user@localhost:22 -j src/test-data/recipe.xml -n 
The [:port][/ssh_port] host arguments are deprecated and ignored, see help for reference
Using ./recipe.01 for job run
Connecting to host: user@localhost, recipe id:796557
** Message: 16:44:38.465: use_pty:FALSE ssh user@localhost -- restraintd --port 0 --stdin

user@localhost's password:
```

```
$ ./src/restraint -t 796557=user@localhost:8081/22 -j src/test-data/recipe.xml -n 
The [:port][/ssh_port] host arguments are deprecated and ignored, see help for reference
Using ./recipe.01 for job run
Connecting to host: user@localhost, recipe id:796557
** Message: 16:43:54.590: use_pty:FALSE ssh user@localhost -- restraintd --port 0 --stdin

user@localhost's password:
```
And proper format works as expected,
```
$ ./src/restraint -t 796557=user@localhost -j src/test-data/recipe.xml -n 
Using ./recipe.01 for job run
Connecting to host: user@localhost, recipe id:796557
** Message: 16:50:20.794: use_pty:FALSE ssh user@localhost -- restraintd --port 0 --stdin

user@localhost's password:
```
