### PR TITLE
Fix noisy output in restraint client

### LINKED ISSUE #87: Output of restraint-client is noisy
The customer reported that output generated by 0.2.1 Restraint seems to contain more output than we were used to seeing before (0.1.45).

This change wasn't intentional and should be further investigated.

### PR DESCRIPTION
**Pull request by danrodrig**
After the removal of libssh, communication between Restraint client and `restraintd` is done through stdout/stderr. In a nutshell, the stdout/stderr from `restraintd` is printed in the client. When `restraintd` is ran by the client, messages sent with `connections_write` are written to `restraintd` stdout too, so these shouldn't be printed outside `connections_write`, otherwise they will be duplicated without proper formatting to match them with the test host. In most cases this was controlled by printing these messages to stderr and suppressing stderr output with a null printer/writer.

- Fix client output format. Print to stdout and include the hostname where the recipe is running
- Add null print handler to suppress `g_printerr` output in `restraintd` when it runs through the client
- Use `g_printerr` for harness logging, which will be suppressed when `restraintd` is ran by the client
- Suppress logging just before main loop starts to avoid hiding start messages 
- Print the process command in the child, to revert to release 0.1.45 behaviour
- Adjust IO callbacks to not output to stdout when `restraintd` is ran by the client and ensure that the buffers are always NULL terminated
- While setting task version, print error from get_package_version to STDERR with g_warning, instead of STDOUT

Resolves #87

### CODE REVIEW

**Comment by StykMartin** [comment]
@danrodrig please fix Brew
```
xmlrpc.client.Fault: <Fault 1: "<class 'psycopg2.extensions.TransactionRollbackError'>: deadlock detected\nLINE 1: UPDATE sessions SET update_time=NOW() WHERE id = 49180675\n               ^\nDETAIL:  Process 6631 waits for RowExclusiveLock on relation 16826 of database 16388; blocked by process 228626.\nProcess 228626 waits for AccessExclusiveLock on relation 34060 of database 16388; blocked by process 6631.\nHINT:  See server log for query details.\n">
```

File: src/client.c [hunk 1]
```diff
@@ -768,10 +768,17 @@ handle_message (const char *message,
 
     jobj = json_tokener_parse(message);
     json_headers = find_object(jobj, "headers");
-    if (!json_headers) {
-        g_message("%s", message);
+
+    /* Every message that is not a JSON object is printed to STDOUT.
+       In a nutshell, these should be restraind own messages, NOT task,
+       NOT harness. */
```
Comment (cbouchar) [inline src/client.c:774]: This doesn't read well.  Isn't restraintd the same as the harness?  Not sure the distinction you are trying to make.  You also have a typo s/restraind/restraintd/

File: src/task.c [hunk 2]
```diff
@@ -1112,9 +1112,8 @@ task_handler (gpointer user_data)
       result = G_SOURCE_CONTINUE;
       break;
   }
-  if (message->len) {
-    if (fwrite(message->str, sizeof(gchar), message->len, stderr) != message->len)
-        g_warning ("failed to write message");
+  if (message->len > 0) {
+    g_printerr ("%s", message->str);
```
Comment (StykMartin) [inline src/task.c:1116]:
```
g_printerr() should not be used from within libraries. 
Instead g_log() or g_log_structured() should be used,
or the convenience macros g_message(), g_warning() and g_error().
```

I think we spoke about g_printerr that we don't want to use it or?

Comment (danrodrig) [reply src/task.c:1116]: In a different context tho. It was discussed for reporting errors within a function, and the comment made was that, instead of printing it, the error should be returned through GError and the caller should decide what to do with it.

In this case, these are harness messages and they should be printed to restraintd stderr.

I used g_printerr instead of fwrite because we need to supress these messages when restraintd runs with the client. And I didn't use g_message or similar to keep output as it was in 0.1.45, as these macros add,
```
** Message: XX:YY:ZZ.NNN: the message...

```

With a new line too.

Also, regarding fwrite, doesn't make much sense to use it with GStrings, as these guarantee that the str member is going to be NULL-terminated.
