### PR TITLE
Fix file descriptor leaks in restraintd

### LINKED ISSUE #215: File descriptor leaks in restraintd
Each task opens two log files (`task.log` and `harness.log`), whose file descriptors leak into child processes spawned by `restraintd` because `close_on_exec` is not set on them.

The leaked file descriptors can lead to failures of tests which would otherwise pass, such as `DSO data reopen` in `perf test`, which mishandles gaps in file descriptor numbering. Gaps in child process file descriptor numbering occur because `restraintd` sets `close_on_exec` on socket file descriptors opened before the log files are opened.

### PR DESCRIPTION
**Pull request by wackrat**
Fixes #215

Commit `d35c836` is sufficient to prevent file descriptors from leaking into child processes.

Commit `8303052` prevents accumulation of open files and the resources associated with them, independently of whether they leak into child processes.

### CODE REVIEW

**Comment by StykMartin** [comment]
Hello @wackrat can you please rebase your change? Thank you.

File: src/task.c [hunk 1]
```diff
@@ -1259,6 +1259,7 @@ task_handler (gpointer user_data)
               stop_uploader (app_data);
 
           rstrnt_upload_logs (task, app_data, soup_session, app_data->cancellable);
+          rstrnt_close_logs (task);
```
Comment (cbouchar) [inline src/task.c:1262]: I'm asking questions to make sure I understand.  Because g_hash_table_remove was NOT called, rstrnt_task_log_data_destroy() was never executed.  Is that correct?

**Review by cbouchar — APPROVED** [review]
Very good! Thank you.

**Comment by StykMartin** [comment]
@cbouchar what was the reason for not merging this one?

**Comment by cbouchar** [comment]
> @cbouchar what was the reason for not merging this one?

@StykMartin @wackrat I would ask the author of the code.

**Comment by StykMartin** [comment]
@cbouchar external contributors don't have the ability to merge PR.
Feel free to merge next time after you approve.

**Comment by StykMartin** [comment]
@wackrat can you please rebase this so we will get the latest results from CI? Thank you!

File: src/task.c (hunk 1 above)
Comment (wackrat) [reply src/task.c:1262]: Yes, that's correct. Prior to the new call to `rstrnt_close_logs` logs were only added to the hash table, not removed. A debugger session on `restraintd` confirmed that log files were closed as a result of the `g_hash_table_remove` call.
